mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
#  type-aliases-package: com.love.*.mapper
  #配置mybatisPlus日志
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  # 应用服务 WEB 访问端口
  port: 8089
logging:
  level:
    root: info
  file:
      # 默认情况下：会在项目的根目录下生成/output/logs/spring.log，默认的日志名是：spring.log
    path: logs
      # 如果不想把日志存放在logging.file.path目录下，可以采用name来重新定义存储的位置和日志文件的名称

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 
    password: 
    url: 
  redis:
    database: 1
    host: 127.0.0.1
    max-active: 20
    max-idle: 0
    max-wait: 1
    min-idle: 0
    password: 
    port: 6379
    timeout: 2000
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
#  http://127.0.0.1:5672
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username:
    password: 
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000
  mail:
    host:
    username: 
    password: 
    default-encoding: UTF-8
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
  elasticsearch:
    rest:
      uris:

token:
  config:
    accessTokenValidity: 1800
    clientId: SOJ_DEMO
    grantTypes: password
    refreshTokenValidity: 36000
    scopes: all
    secret: soj@123
  isRefreshToken: false
  resourceId: SOJ_DEMO
  signingKey: SOJ_SYMMETRY

search:
  mode: elasticsearch

# 本地存储图片上传地址
file-upload-config:
  #图片存储路径
  image-real-path: 
  #图片的映射路径
  image-mapper-path: 
  #后端地址
  host-ip: http://127.0.0.1:8089
  #默认头像
  default-avatar: /image/default-avatar.png
  #默认昵称
  default-nickname: 菜鸟学霸

#阿里云 OSS存储
aliyun:
  oss:
    endpoint:
    accessKeyId:
    accessKeySecret:
    bucketName: 18066

