mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
#  type-aliases-package: com.love.*.mapper
  #配置mybatisPlus日志
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  # 应用服务 WEB 访问端口
  port: 8089
logging:
  level:
    root: info
  file:
      # 默认情况下：会在项目的根目录下生成/output/logs/spring.log，默认的日志名是：spring.log
    path: logs
      # 如果不想把日志存放在logging.file.path目录下，可以采用name来重新定义存储的位置和日志文件的名称
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/school?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&useAffectedRows=true&allowPublicKeyRetrieval=true
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: root
    max-active: 20
    max-idle: 0
    max-wait: 1
    min-idle: 0
    timeout: 200000
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
      # jackson时间格式化
  jackson:
     time-zone: GMT+8
     date-format: yyyy-MM-dd HH:mm:ss
#  http://127.0.0.1:5672
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000
  mail:
    host: smtp.qq.com
    username: 1803466516@qq.com
    password: hjnvjyvlptlleihc
    default-encoding: UTF-8
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
  elasticsearch:
    rest:
      uris: 127.0.0.1:9200
      username: elastic
      password: xyl666
token:
  config:
    accessTokenValidity: 1800
    clientId: SOJ_DEMO
    grantTypes: password
    refreshTokenValidity: 36000
    scopes: all
    secret: soj@123
  isRefreshToken: false
  resourceId: SOJ_DEMO
  signingKey: SOJ_SYMMETRY

search:
  mode: elasticsearch

# 本地存储图片上传地址
file-upload-config:
  #图片存储路径
  image-real-path: D:\school\image\
  #图片的映射路径
  image-mapper-path: /image/
  #后端地址
  host-ip: http://127.0.0.1:8089
  #默认头像
  default-avatar: /image/default-avatar.png
  #默认昵称
  default-nickname: 菜鸟学霸

#阿里云 OSS存储
aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tGJNawrKddsDfHy4Wh7
    accessKeySecret: 9UK615Nd0YMQgIgguAxCaFJnKt6j7O
    bucketName: 18066
baidu:
  api:
    appId: 40771445
    apiKey: 0V4kRYERR0A9KMhv8EsH608X
    secretKey: A6aVDlBwDo5mabU0n3XPfS9HM5sglSV5

